spring:
  config:
    import: application-secret.properties

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fcm-test-db;DATABASE_TO_UPPER=FALSE;mode=mysql  # H2 접속 정보 (전부 소문자로 지정)
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

fcm:
  key:
    path: ${FCM_KEY_PATH}
    scope: https://www.googleapis.com/auth/cloud-platform
  api:
    url: https://fcm.googleapis.com/v1/projects/${FCM_PROJECT_ID}/messages:send